from enum import StrEnum


class ScamSignal(StrEnum):
    BANK_CLAIM = "BANK_CLAIM"
    GOVERNMENT_CLAIM = "GOVERNMENT_CLAIM"
    TECH_SUPPORT_CLAIM = "TECH_SUPPORT_CLAIM"
    FAMILY_EMERGENCY = "FAMILY_EMERGENCY"

    OTP_MENTION = "OTP_MENTION"
    OTP_REQUEST = "OTP_REQUEST"
    PASSWORD_REQUEST = "PASSWORD_REQUEST"
    PIN_REQUEST = "PIN_REQUEST"

    MONEY_TRANSFER_REQUEST = "MONEY_TRANSFER_REQUEST"
    GIFT_CARD_REQUEST = "GIFT_CARD_REQUEST"
    REMOTE_ACCESS_REQUEST = "REMOTE_ACCESS_REQUEST"

    URGENCY = "URGENCY"
    THREAT = "THREAT"
    SECRECY = "SECRECY"
